### ISSUE TITLE
Select inside data table row not rendering select menu outside of row

### ISSUE THREAD

**Issue by Kestami** [balmjs/balm-ui#91]
Development Relevant Information:

BalmUI version: 9.38.2
Browser: Chrome
Operating System: Win 10

Hi,

I've got a select input sat inside a slot in a datatable (simplified example):

Markup:

```
<ui-table :data="requestData"
                :thead="thead"
                :tbody=tbody"

   <template #selectInput="{ data }">
                     <ui-select v-model='mySelectedValue'
                                      :options='myOptions'>
                        Label
                     </ui-select>
</ui-table>
```

data:

```
data() {
   return {
      thead: [
         'selectColumn'
      ],
      tbody: [
         {
            slot: 'selectInput'
         }
      ],
      requestData: [
         mySelectedValue: '',
         myOptions: [
             {
                label: 'option 1',
                value: 1
             },
             {
                label: 'option 2',
                value: 2
             }
         ]
      ]
   }
}
```

However when you click the ui-select to drop down it's selectable options, the menu doesn't render outside of the table row (i.e. you can barely see any more than the original select input).

I've had a quick look at the CSS applied hoping there was maybe an overflow: hidden on the table row but I can't see anything.

Any ideas?

Cheers.

**Comment by Kestami** [comment]
Hi,

Apologies for chasing, any update on this?

Cheers.

**Comment by elf-mouse** [comment]
Hi @Kestami ,

This container `overflow: hidden` problem is caused by the official MDC design principles.

Please see this [comment](https://github.com/balmjs/balm-ui/issues/24#issuecomment-740441232) in another issue for the solution.

**Comment by HDShabe** [comment]
Hi @elf-mouse 

Has something changed here? I just ran some tests. If I downgrade back to v9.42.3 they're as they were when we spoke above back in December. This is a select that's part of a template cell in a datatable as before.

![image](https://user-images.githubusercontent.com/42472545/166911255-41cceebe-98cf-44d7-9fc1-e4602e49b06a.png)

However I was on version 10.4.1 and noticed the following (I've updated to 10.5.0 and it's still the same)

![image](https://user-images.githubusercontent.com/42472545/166912584-514fc251-0901-4ac6-ac2a-a1a9303a608d.png)

the select options now take up most of the height of the screen and give the page itself a scrollbar, rather than the options dropdown having a scrollbar. I don't mind this so much but I have some selects with a fair few options in them and it's cutting off a portion of the options at the start, I can scroll down to the end but the ones at the top I can't get to without using arrow keys.

Any ideas?

Thanks as always : )

**Comment by HDShabe** [comment]
Hi @elf-mouse 

Any update/info on this one?

Thanks!

**Comment by elf-mouse** [comment]
Sorry @HDShabe , I haven't figured out how to adjust it yet, suggesting a temporary use of css rewriting to fix the style problem

**Comment by HDShabe** [comment]
No worries at all, can we reopen the ticket? 

Cheers!

**Comment by HDShabe** [comment]
Hi @elf-mouse  

Any official fix in the pipeline for this?

Cheers.

**Comment by elf-mouse** [comment]
Hi @HDShabe , please upgrade to `10.9.0`, this css bug has been fixed.

Thanks again :)

**Comment by HDShabe** [comment]
Hi @elf-mouse  

That looks much better! It's only a very slight noticeable thing but it seems like there's an outer scroll on the option elements, see below.

![image](https://user-images.githubusercontent.com/42472545/178009692-6344384a-cd4f-4ec0-961b-b0a5e40ee9f5.png)

Then you seem to be able to scroll a tiny bit more

![image](https://user-images.githubusercontent.com/42472545/178009879-7f617df6-741a-4483-abc3-823abf4f8640.png)

It is minor, I'm happy with the fix for now but thought it was worth raising it with you!

What do you think?

Cheers!

**Comment by elf-mouse** [comment]
Hi @HDShabe , it's MDC list default style, you can overwrite css in your global definition css:

```scss
.mdc-deprecated-list {
  padding: 0;
}
```
